### 1. Create a NumPy Array
Create a 1D NumPy array of integers from 0 to 9.

In [6]:
# Your code here
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Unit test
import numpy as np
assert (arr == np.arange(10)).all(), 'Array does not match expected range.'

### 2. Reshape an Array
Reshape the array from the previous exercise into a 2x5 matrix.

In [8]:
# Your code here
arr = arr.reshape((2, 5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
# Unit test
assert arr.shape == (2, 5), 'Shape is not 2x5.'

### 3. Element-wise Operations
Multiply each element in the reshaped array by 2.

In [10]:
# Your code here
arr = arr * 2
print(arr)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [11]:
# Unit test
assert (arr == np.arange(10).reshape(2,5)*2).all(), 'Elements not correctly multiplied.'

### 4. Boolean Masking
Extract all elements from the array greater than 10.

In [13]:
# Your code here
result = arr[arr > 10]
print(result)

[12 14 16 18]


In [14]:
# Unit test
assert (result == arr[arr > 10]).all(), 'Incorrect boolean masking.'

### 5. Mean and Standard Deviation
Compute the mean and standard deviation of the array.

In [15]:
# Your code here
mean = np.mean(arr)
std = np.std(arr)

In [16]:
# Unit test
assert abs(mean - np.mean(arr)) < 1e-6 and abs(std - np.std(arr)) < 1e-6, 'Incorrect mean or std.'

### 6. Matrix Multiplication
Multiply a 2x3 matrix with a 3x2 matrix using `@` operator.

In [17]:
# Your code here
A = np.random.rand(2, 3)
B = np.random.rand(3, 2)

result = A @ B
print(result)

[[1.24868846 0.74288642]
 [0.77011034 0.6273925 ]]


In [18]:
# Unit test
assert result.shape == (2, 2), 'Resulting shape incorrect.'

### 7. Broadcasting
Add a 1D array [1, 2, 3] to each row of a 3x3 matrix using broadcasting.

In [22]:
# Your code here
matrix = np.array([[1, 3, 9],
                   [3, 4, 8],
                   [2, 0, 1]])

vector = np.array([1, 2, 3])

result = matrix + vector
print(result)

[[ 2  5 12]
 [ 4  6 11]
 [ 3  2  4]]


In [24]:
# Unit test
expected = np.array([[1,3,9],[3,4,8],[2,0,1]]) + np.array([1,2,3])
assert (result == expected).all(), 'Broadcasting failed.'

### 8. Random Numbers
Generate a 3x3 array of random numbers from a normal distribution with mean 0 and std 1.

In [25]:
# Your code here
result = np.random.normal(loc=0.0, scale=1.0, size=(3, 3))

In [26]:
# Unit test
assert result.shape == (3,3), 'Shape incorrect.'

### 9. Argmax and Argmin
Find the indices of the maximum and minimum values in a 1D array.

In [27]:
# Your code here
arr = np.array([3, 7, 2, 9, 1, 5])

max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

In [28]:
# Unit test
assert arr[max_idx] == max(arr) and arr[min_idx] == min(arr), 'Incorrect indices for max or min.'

### 10. Save and Load Arrays
Save an array to disk using `np.save` and load it back using `np.load`.

In [31]:
# Your code here
import os
arr = np.array([1, 2, 3, 4, 5])

np.save('my_array.npy', arr)

loaded_arr = np.load('my_array.npy')

In [32]:
# Unit test
np.save('test.npy', arr)
loaded = np.load('test.npy')
os.remove('test.npy')
assert (loaded == arr).all(), 'Saved and loaded array do not match.'